#ifndef PIC_COM_BAC_CONTEXTS_H
#define PIC_COM_BAC_CONTEXTS_H

// Context offsets for CP slices
#define CTX_CODED_BLOCK_FLAG_OFFSET		(0)
#define CTX_LAST_SIG_PREFIX_OFFSET		(CTX_CODED_BLOCK_FLAG_OFFSET + 1)
#define CTX_SIG_FLAG_OFFSET				(CTX_LAST_SIG_PREFIX_OFFSET + 1)
#define CTX_ABS_COEFF_GREATER_1_OFFSET	(CTX_SIG_FLAG_OFFSET + 16)
#define CTX_ABS_COEFF_GREATER_2_OFFSET	(CTX_ABS_COEFF_GREATER_1_OFFSET + 1)
#define CTX_ABS_COEFF_LEVEL_OFFSET		(CTX_ABS_COEFF_GREATER_2_OFFSET + 1)
#define NUM_CPS_CONTEXT					(CTX_ABS_COEFF_LEVEL_OFFSET + 1)

// Context bases for coding pyramids
#define CTX_CP_LUMA_BASE(N)				(N * NUM_CPS_CONTEXT)
#define CTX_CP_CHROMA_BASE(N)			(CTX_CP_LUMA_BASE(5) + N * NUM_CPS_CONTEXT)
#define NUM_CP_CONTEXT					(CTX_CP_CHROMA_BASE(5))

// Contexts for the prediction modes
#define CTX_PRED_MODE_NN				(NUM_CP_CONTEXT)
#define CTX_PRED_COPY_MODE_FLAG			(CTX_PRED_MODE_NN)
#define NUM_PB_CONTEXT					(CTX_PRED_COPY_MODE_FLAG + 1)

//// Contexts for the Residual Transform Blocks (RTBs)
//#define CTX_RTB_CODE_BLOCK_OFFSET			(0)
//#define CTX_RTB_LAST_SIG_COARSE_OFFSET		(CTX_RTB_CODE_BLOCK_OFFSET + 1)
//#define CTX_RTB_LAST_SIG_FINE_OFFSET		(CTX_RTB_LAST_SIG_COARSE_OFFSET + 1)
//#define CTX_RTB_SIG_FLAG_OFFSET				(CTX_RTB_LAST_SIG_FINE_OFFSET + 1)
//#define CTX_RTB_ABS_COEFF_GREATER_1_OFFSET	(CTX_RTB_SIG_FLAG_OFFSET + 64)
//#define CTX_RTB_ABS_COEFF_GREATER_2_OFFSET	(CTX_RTB_ABS_COEFF_GREATER_1_OFFSET + 1)
//#define CTX_RTB_ABS_COEFF_LEVEL_OFFSET		(CTX_RTB_ABS_COEFF_GREATER_2_OFFSET + 1)
//#define NUM_RTB_COMP_CONTEXT				(CTX_RTB_ABS_COEFF_LEVEL_OFFSET + 1)
//
//#define CTX_RTB_LUMA_BASE					(CTX_PB_BASE + NUM_PB_CONTEXT)
//#define CTX_RTB_CHROMA_BASE					(CTX_RTB_LUMA_BASE + NUM_RTB_COMP_CONTEXT)
//#define NUM_RTB_CONTEXT						(2 * NUM_RTB_COMP_CONTEXT)
//
//#define NUM_TOTAL_CONTEXT					(NUM_CP_CONTEXT + NUM_PB_CONTEXT + NUM_RTB_CONTEXT)
#define NUM_TOTAL_CONTEXT					(NUM_CP_CONTEXT)

#endif
