#ifndef PIC_COM_BAC_CONTEXTS_H
#define PIC_COM_BAC_CONTEXTS_H

// Contexts for the core block
#define CTX_CORE_CODED_BLOCK_FLAG		(0)
#define CTX_CORE_LAST_SIG_PREFIX		(CTX_CORE_CODED_BLOCK_FLAG + 1)
#define CTX_CORE_SIG_FLAG				(CTX_CORE_LAST_SIG_PREFIX + 1)
#define CTX_CORE_ABS_COEFF_GREATER_1	(CTX_CORE_SIG_FLAG + 16)
#define CTX_CORE_ABS_COEFF_GREATER_2	(CTX_CORE_ABS_COEFF_GREATER_1 + 1)
#define CTX_CORE_ABS_COEFF_LEVEL		(CTX_CORE_ABS_COEFF_GREATER_2 + 1)

// Contexts for the basis selectors
#define CTX_BASIS_COPY_FLAG				(CTX_CORE_ABS_COEFF_LEVEL + 1)

// Context offsets for each microbasis component
#define CTX_CODED_QUADRANT_OFFSET		(0)
#define CTX_CODED_BLOCK_FLAG_OFFSET		(CTX_CODED_QUADRANT_OFFSET + 1)
#define CTX_LAST_SIG_PREFIX_OFFSET		(CTX_CODED_BLOCK_FLAG_OFFSET + 1)
#define CTX_SIG_FLAG_OFFSET				(CTX_LAST_SIG_PREFIX_OFFSET + 1)
#define CTX_ABS_COEFF_GREATER_1_OFFSET	(CTX_SIG_FLAG_OFFSET + 16)
#define CTX_ABS_COEFF_GREATER_2_OFFSET	(CTX_ABS_COEFF_GREATER_1_OFFSET + 1)
#define CTX_ABS_COEFF_LEVEL_OFFSET		(CTX_ABS_COEFF_GREATER_2_OFFSET + 1)
#define NUM_QUADRANT_CONTEXT			(CTX_ABS_COEFF_LEVEL_OFFSET + 1)

// Context bases for coding pyramids
#define CTX_QUADRANT_BASE(N)			(CTX_BASIS_COPY_FLAG + 1 + N * NUM_QUADRANT_CONTEXT)
//#define CTX_CP_CHROMA_BASE(N)			(CTX_CP_LUMA_BASE(5) + N * NUM_CPS_CONTEXT)

#define NUM_TOTAL_CONTEXT				(CTX_QUADRANT_BASE(12))

#endif
